---
name: Terraform Apply
on:
  push:
    branches:
      - main
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.1.0
          terraform_wrapper: false
        run: |+
          terraform init
          terraform apply -auto-approve
            
